# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'ios-remote-push' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'ObjectMapper', '~> 2.2'

  # Pods for ios-remote-push

  target 'ios-remote-pushTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
